{{- if .Values.gitea.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-ofc-gitea-ebs-volume-clain
  labels:
    app: {{ template "osm-for-cities.name" . }}
    component: ofc-gitea-ebs-volume-clain
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: "gp2"
  resources:
    requests:
      storage: 20Gi
{{- end }}