version: "3"
networks:
  gitea:
    external: false
services:
  server:
    image: developmentseed/osm-for-cities-gitea:v1
    build:
      context: ./gitea
      dockerfile: Dockerfile
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA_CUSTOM=/data
    restart: always
    networks:
      - gitea
    volumes:
      - ./app-data/gitea/data:/data
      - ./app-data/gitea/ssh:/data/git/.ssh
      # - ./gitea/custom:/gitea-custom
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "127.0.0.1:2222:22"
  runner_setup:
    image: developmentseed/osm-for-cities-runner:v1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./app-data:/home/runner/app/app-data
      # - ./:/home/runner/app
    command: "/home/runner/app/setup.sh"
    env_file:
      - ./.env
  runner_update:
    image: developmentseed/osm-for-cities-runner:v1
    volumes:
      - ./app-data:/home/runner/app/app-data
      # - ./:/home/runner/app
    command: "/home/runner/app/update.sh"
    env_file:
      - ./.env
