version: "3"

services:
  runner:
    platform: linux/amd64
    build: .
    volumes:
      - ./docker-data/runner:/home/runner
      - app-data:/home/runner/app
volumes:
  app-data:
    driver: local
    driver_opts:
      type: none
      device: .
      o: bind
