version: "3"
networks:
  gitea:
    external: false
services:
  server:
    image: gitea/gitea:1.19.0
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - ./app-data/docker/gitea/data:/data
      - ./app-data/docker/gitea/ssh:/data/git/.ssh
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "127.0.0.1:2222:22"
  runner_setup:
    image: developmentseed/osm-for-cities-runner:v1
    build:
          context: ./
          dockerfile: Dockerfile
    volumes:
      - ./app-data:/home/runner/app/app-data
      # - ./:/home/runner/app
    command: "/home/runner/app/setup.sh"
    env_file:
      - ./.env
  runner_update:
    image: developmentseed/osm-for-cities-runner:v1
    volumes:
      - ./app-data:/home/runner/app/app-data
      # - ./:/home/runner/app
    command: "/home/runner/app/update.sh"
    env_file:
      - ./.env