## Namespace
namespace: default

## Enviroment, value for NODE_ENV
environment: development

# Cloud provider
cloudProvider: aws

AWS_SSL_ARN: false
serviceType: NodePort

# Domain
domain: staging.osmforcities.org
adminEmail: admin@osmforcities.org

# ====================================================
# Gitea App
# ====================================================
gitea:
  enabled: true
  image:
    name: gitea/gitea
    tag: latest
  persistenceDisk:
    enabled: true
    AWS_ElasticBlockStore_volumeID: vol-023a12f7daf1b71ac
    AWS_ElasticBlockStore_size: 20Gi
  nodeSelector:
    enabled: true
    label_key: nodegroup_type
    label_value: web

# ====================================================
# Runner config
# ====================================================
runner:
  enabled: true
  image:
    name: developmentseed/osm-for-cities-runner
    # tag: 0.1.0-0.dev.git.196.hb9b3886
  env:
    GITEA_ACCESS_TOKEN: "{{GITEA_ACCESS_TOKEN}}"
    GITEA_HOST_URL: https://staging.osmforcities.org
    TMP_DIR: /home/runner/app/app-data/tmp
    GITEA_USER: runner
    GITEA_EMAIL: runner@osmforcities.org
  efs:
    volumeHandle: fs-032240e3968a5fa76
  ## Setup
  setup:
    enabled: true
    # schedule: "*/1 * * * *"
    schedule: "0 0 * * 0"
    nodeSelector:
      enabled: true
      label_key: nodegroup_type
      label_value: data_processing
  ## Update
  update:
    enabled: true
    # schedule: "*/1 * * * *"
    schedule: "0 */5 * * *"
    nodeSelector:
      enabled: true
      label_key: nodegroup_type
      label_value: data_processing
