ofcVersion: develop-9302179

## Aplication enviroment
environment: development

cloudProvider: aws
AWS_SSL_ARN: false
serviceType: NodePort
domain: osmforcities.org
adminEmail: admin@osmforcities.org

# ====================================================
# Gitea App
# ====================================================
gitea:
  enabled: true
  image:
    name: gitea/gitea
    tag: latest
  nodeSelector:
    enabled: true
    label_key: nodegroup_type
    label_value: web

# ====================================================
# EFS config
# ====================================================
efs:
  enable: true


# ====================================================
# Runner config
# ====================================================
runner:
  enabled: true
  env:
    GITEA_ACCESS_TOKEN: "{{ GITEA_ACCESS_TOKEN }} "
    GITEA_HOST_URL: http://k8s-default-developo-2445a359ae-1728892866.us-east-1.elb.amazonaws.com
    TMP_DIR: /home/runner/app/app-data/tmp
    GITEA_USER: runner
    GITEA_EMAIL: runner@osmforcities.org
  efs:
    volumeHandle: fs-05e2fafbbf674d06f
# ====================================================
# Runner setup
# ====================================================
runner_setup:
  enabled: true
  image:
    name: developmentseed/osm-for-cities-runner
    tag: v6
  # schedule: "0 0 * * 0" # Every Sunday at midnight
  schedule: "*/60 * * * *"
  nodeSelector:
    enabled: true
    label_key: nodegroup_type
    label_value: data_processing
# ====================================================
# Runner update
# ====================================================
runner_update:
  enabled: true
  image:
    name: developmentseed/osm-for-cities-runner
    tag: v6
  schedule: "*/1 * * * *"
  nodeSelector:
    enabled: true
    label_key: nodegroup_type
    label_value: data_processing
