## Namespace
namespace: default

## Enviroment, value for NODE_ENV
environment: production

# Cloud provider
cloudProvider: aws

AWS_SSL_ARN: false
serviceType: NodePort

# Domain
domain: staging.osmforcities.org
adminEmail: admin@osmforcities.org

# ====================================================
# Gitea App
# ====================================================
gitea:
  enabled: true
  image:
    name: gitea/gitea
    tag: latest
  persistenceDisk:
    enabled: false
    AWS_ElasticBlockStore_volumeID: vol-0404b12c401b3f186
    AWS_ElasticBlockStore_size: 20Gi
  nodeSelector:
    enabled: true
    label_key: nodegroup_type
    label_value: web

# ====================================================
# Runner config
# ====================================================
runner:
  enabled: true
  image:
    name: developmentseed/osm-for-cities-runner
    tag: v0.1.0-0.dev.git.167.h3c28136
  env:
    GITEA_ACCESS_TOKEN: "ddd"
    GITEA_HOST_URL: "http://k8s-default-developo-c674a237c8-459472354.us-east-1.elb.amazonaws.com"
    TMP_DIR: /home/runner/app/app-data/tmp
    GITEA_USER: runner
    GITEA_EMAIL: runner@osmforcities.org
  efs:
    volumeHandle: fs-032240e3968a5fa76
  ## Setup
  setup:
    enabled: false
    # schedule: "*/1 * * * *"
    schedule: "0 0 * * 0"
    nodeSelector:
      enabled: true
      label_key: nodegroup_type
      label_value: data_processing
  ## Update
  update:
    enabled: true
    schedule: "*/1 * * * *"
    # schedule: "0 0 * * *"
    nodeSelector:
      enabled: true
      label_key: nodegroup_type
      label_value: data_processing
