## Enviroment
environment: development

# Cloud provider
cloudProvider: aws

AWS_SSL_ARN: false
serviceType: NodePort

# Domain
domain: osmforcities.org
adminEmail: admin@osmforcities.org

# ====================================================
# Gitea App
# ====================================================
gitea:
  enabled: true
  image:
    name: gitea/gitea
    tag: latest
  nodeSelector:
    enabled: true
    label_key: nodegroup_type
    label_value: web

# ====================================================
# Runner config
# ====================================================
runner:
  enabled: true
  image:
    name: developmentseed/osm-for-cities-runner
    tag: 0.1.0-0.dev.git.154.hada9acf
  env:
    GITEA_ACCESS_TOKEN: "{{ GITEA_ACCESS_TOKEN }}"
    GITEA_HOST_URL: http://k8s-default-developo-2445a359ae-1728892866.us-east-1.elb.amazonaws.com
    TMP_DIR: /home/runner/app/app-data/tmp
    GITEA_USER: runner
    GITEA_EMAIL: runner@osmforcities.org
  efs:
    volumeHandle: fs-05e2fafbbf674d06f # this calue comes from terraform output
  ## Setup
  setup:
    enabled: false
    schedule: "*/60 * * * *" #"0 0 * * 0"
    nodeSelector:
      enabled: true
      label_key: nodegroup_type
      label_value: data_processing
  ## Update
  update:
    enabled: true
    schedule: "*/10 * * * *"
    nodeSelector:
      enabled: true
      label_key: nodegroup_type
      label_value: data_processing
