apiVersion: v1
kind: Service
metadata:
  name: gitea-service
  namespace: default
spec:
  # ports:
  #   - name: http
  #     port: 3000
  #     targetPort: 3000
  ports:
    - port: 3000
      protocol: TCP
  type: ClusterIP
  selector:
    app:  ofc-app