apiVersion: batch/v1
kind: CronJob
metadata:
  name: ofc-runner-update
spec:
  schedule: "*/2 * * * *" # Every day
  startingDeadlineSeconds: 10
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: ofc-runner-update-container
              image: developmentseed/osm-for-cities-runner:v5
              # command: ["/home/runner/app/update.sh"]
              command: ["/bin/sh"]
              args: 
                - -c
                - |
                  echo 'Start updating...';
                  if [ -f "${TMP_DIR}/history-latest.osh.pbf" ]; then
                      yarn cli update-presets-history --recursive
                      yarn cli context cities-of-brazil update
                  fi
              env:
                - name: NODE_ENV
                  value: production
                - name: GITEA_ACCESS_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: runner-secret
                      key: GITEA_ACCESS_TOKEN
                - name: GITEA_HOST_URL
                  valueFrom:
                    secretKeyRef:
                      name: runner-secret
                      key: GITEA_HOST_URL
                - name: GIT_REPOSITORY_URL
                  valueFrom:
                    secretKeyRef:
                      name: runner-secret
                      key: GIT_REPOSITORY_URL
                - name: TMP_DIR
                  valueFrom:
                    secretKeyRef:
                      name: runner-secret
                      key: TMP_DIR
                - name: GITEA_USER
                  valueFrom:
                    secretKeyRef:
                      name: runner-secret
                      key: GITEA_USER
                - name: GITEA_EMAIL
                  valueFrom:
                    secretKeyRef:
                      name: runner-secret
                      key: GITEA_EMAIL
              volumeMounts:
                - name: runner-efs-volume
                  mountPath: /home/runner/app/app-data
          volumes:
            - name: runner-efs-volume
              persistentVolumeClaim:
                claimName: ofc-runner-efs-volume-claim
          restartPolicy: Never #OnFailure
          nodeSelector:
            nodegroup_type: data_processing
