---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ofc-runner-presets-history-efs-volume
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - tls
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-05e2fafbbf674d06f
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ofc-runner-presets-history-efs-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  volumeName: ofc-runner-presets-history-efs-volume
  resources:
    requests:
      storage: 5Gi