apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ofc-runner-ebs-volume-clain
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: "gp2"
  resources:
    requests:
      storage: 1Gi
